# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_pkmn'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_pkmn'

# Base path for your project using an environment variable in your shell
# You cannot use Jinja templating here. Just mention the folders relative to the project.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  dbt_pkmn:
      +materialized: view  # This applies to models in the "models/example/" directory
