version: 2

sources:
  - name: pokemart
    schema: main
    tables:
      - name: dimCustomers
      - name: dimProducts
      - name: dimProdCategories
      - name: dimTime
      - name: factSales


